<?php

namespace App\Services;

use App\Models\Setting;

class ThemeService
{
    protected $defaultTheme = [
        "primary" => "#2d208d",
        "secondary" => "#2f6a60",
        "success" => "#00b315",
        "info" => "#00d5ff",
        "warning" => "#f1b83b",
        "danger" => "#db0000",
        "light" => "#ededed",
        "dark" => "#000000"
    ];

    /**
     * Get theme colors from database with fallback to defaults.
     *
     * @return array
     */
    public function getThemeColors(): array
    {
        if (Setting::where('key', 'Theme Color')->exists()) {
            $settingVal = Setting::where('key', 'Theme Color')->first()->val;
            $theme = json_decode($settingVal, true);
            if ($theme && isset($theme['primary'])) {
                return array_merge($this->defaultTheme, $theme);
            }
            
            // If it is a simple hex color string
            if ($settingVal && strpos($settingVal, '#') === 0) {
                return array_merge($this->defaultTheme, ['primary' => $settingVal]);
            }
        }

        return $this->defaultTheme;
    }

    /**
     * Ensure the theme.css file exists in the public directory.
     *
     * @return void
     */
    public function ensureThemeCssExists(): void
    {
        $path = public_path('css/theme.css');
        if (!file_exists($path)) {
            $colors = $this->getThemeColors();
            $this->generateThemeCss($colors);
        }
    }

    /**
     * Generate the theme.css file containing CSS custom properties and utility classes.
     *
     * @param array $colors
     * @return void
     */
    public function generateThemeCss(array $colors): void
    {
        $css = "/* Dynamic theme overrides generated by ThemeService */\n";
        $css .= ":root {\n";
        foreach ($colors as $name => $color) {
            $css .= "    --bs-{$name}: {$color};\n";
            $rgb = $this->hex2rgb($color);
            $css .= "    --bs-{$name}-rgb: {$rgb};\n";
            $css .= "    --theme-{$name}: {$color};\n";
            $css .= "    --theme-{$name}-rgb: {$rgb};\n";
        }
        $css .= "}\n\n";

        foreach ($colors as $name => $color) {
            $rgb = $this->hex2rgb($color);
            $darker = $this->adjustBrightness($color, -30);
            
            // Background color utilities
            $css .= ".bg-{$name} {\n";
            $css .= "    background-color: {$color} !important;\n";
            $css .= "}\n";
            
            // Text color utilities
            $css .= ".text-{$name} {\n";
            $css .= "    color: {$color} !important;\n";
            $css .= "}\n";
            
            // Border color utilities
            $css .= ".border-{$name} {\n";
            $css .= "    border-color: {$color} !important;\n";
            $css .= "}\n";

            // Button components
            $css .= ".btn-{$name} {\n";
            $css .= "    background-color: {$color} !important;\n";
            $css .= "    border-color: {$color} !important;\n";
            $css .= "    color: " . ($name === 'light' ? '#000' : '#fff') . " !important;\n";
            $css .= "}\n";
            $css .= ".btn-{$name}:hover, .btn-{$name}:focus, .btn-{$name}:active, .btn-{$name}.active {\n";
            $css .= "    background-color: {$darker} !important;\n";
            $css .= "    border-color: {$darker} !important;\n";
            $css .= "    color: " . ($name === 'light' ? '#000' : '#fff') . " !important;\n";
            $css .= "}\n";
            $css .= ".btn-{$name}:focus {\n";
            $css .= "    box-shadow: 0 0 0 0.25rem rgba({$rgb}, 0.5) !important;\n";
            $css .= "}\n";

            // Outline buttons
            $css .= ".btn-outline-{$name} {\n";
            $css .= "    color: {$color} !important;\n";
            $css .= "    border-color: {$color} !important;\n";
            $css .= "}\n";
            $css .= ".btn-outline-{$name}:hover, .btn-outline-{$name}:focus, .btn-outline-{$name}:active, .btn-outline-{$name}.active {\n";
            $css .= "    background-color: {$color} !important;\n";
            $css .= "    border-color: {$color} !important;\n";
            $css .= "    color: " . ($name === 'light' ? '#000' : '#fff') . " !important;\n";
            $css .= "}\n";
        }

        // Custom UI element overrides
        $css .= "
/* Theme specific navbar elements and accents */
.navbar-custom, .bg-primary-glow {
    background: var(--bs-primary) !important;
}
.sidebar-link.active, .active-link {
    background-color: rgba(var(--bs-primary-rgb), 0.08) !important;
    color: var(--bs-primary) !important;
    border-left: 4px solid var(--bs-primary) !important;
}
.accordion-button:not(.collapsed) {
    background-color: rgba(var(--bs-primary-rgb), 0.05) !important;
    color: var(--bs-primary) !important;
}
";

        if (!file_exists(public_path('css'))) {
            @mkdir(public_path('css'), 0755, true);
        }
        @file_put_contents(public_path('css/theme.css'), $css);
    }

    /**
     * Convert HEX color to RGB color string.
     *
     * @param string $hex
     * @return string
     */
    public function hex2rgb(string $hex): string
    {
        $hex = str_replace("#", "", $hex);
        if (strlen($hex) == 3) {
            $r = hexdec(substr($hex, 0, 1) . substr($hex, 0, 1));
            $g = hexdec(substr($hex, 1, 1) . substr($hex, 1, 1));
            $b = hexdec(substr($hex, 2, 1) . substr($hex, 2, 1));
        } else {
            $r = hexdec(substr($hex, 0, 2));
            $g = hexdec(substr($hex, 2, 2));
            $b = hexdec(substr($hex, 4, 2));
        }
        return "$r, $g, $b";
    }

    /**
     * Adjust brightness of HEX color (positive = lighter, negative = darker).
     *
     * @param string $hex
     * @param int $steps
     * @return string
     */
    public function adjustBrightness(string $hex, int $steps): string
    {
        $steps = max(-255, min(255, $steps));
        $hex = str_replace('#', '', $hex);
        if (strlen($hex) == 3) {
            $hex = str_repeat(substr($hex, 0, 1), 2) . str_repeat(substr($hex, 1, 1), 2) . str_repeat(substr($hex, 2, 1), 2);
        }
        $color_parts = str_split($hex, 2);
        $return = '#';
        foreach ($color_parts as $color) {
            $dec = hexdec($color);
            $dec = max(0, min(255, $dec + $steps));
            $return .= str_pad(dechex($dec), 2, '0', STR_PAD_LEFT);
        }
        return $return;
    }
}
